### ISSUE TITLE
[BUG] color change when copy image!!! Again 

### ISSUE THREAD

**Issue by wolfkingal2000** [Sanster/IOPaint#332]
color change when copy image!!! Again  for color like is video recording 
system: - Platform: Linux-5.15.107+-x86_64-with-glibc2.31
- Python version: 3.10.12
- torch: 2.0.0+cu118
- torchvision: 0.15.1+cu118
- Pillow: 8.4.0
- diffusers: 0.16.1
- transformers: 4.27.4
- opencv-python: 4.7.0.72
- xformers: 0.0.19
- accelerate: 0.20.3
- lama-cleaner: 1.2.1
- rembg: N/A
- realesrgan: 0.3.0
- gfpgan: 1.3.8

and get this error: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/serving.py", line 325, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/socketio/server.py", line 607, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/engineio/server.py", line 428, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.10/dist-packages/engineio/server.py", line 637, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'

https://github.com/Sanster/lama-cleaner/assets/131250049/7d229c66-c070-4e4e-a95f-88ef2505542a

**Comment by Sanster** [comment]
hi, can you upload the test image, so I can reproduce the bug?

**Comment by wolfkingal2000** [comment]
> hi, can you upload the test image, so I can reproduce the bug?
this image i use 

![ghjk](https://github.com/Sanster/lama-cleaner/assets/131250049/83983d05-8a24-4be7-a6f2-2fbf304ddc1a)

**Comment by wolfkingal2000** [comment]
> hi, can you upload the test image, so I can reproduce the bug?

hi can you fix faster?  Thanks you

**Comment by Sanster** [comment]
Hi, I used your picture and followed the steps demonstrated in your video but did not notice any color changes. The copy operation was performed in the browser. I suggest upgrading your browser or trying a different one.
