### ISSUE TITLE
[BUG] PermissionError: [WinError 5]

### ISSUE THREAD

**Issue by Gazgiza** [Sanster/IOPaint#401]
Hi! When I try to launch lama cleaner after installing it with the one click installer it show : "PermissionError: [WinError 5] acess denied to C:\\Users\\myuser"
Here is the full log:
""- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.6
- torch: 1.13.1+cu117
- torchvision: 0.14.1+cu117
- Pillow: 10.0.0
- diffusers: 0.16.1
- transformers: 4.27.4
- opencv-python: 4.8.0.76
- xformers: 0.0.16
- accelerate: N/A
- lama-cleaner: 1.2.5
- rembg: 2.0.50
- realesrgan: 0.3.0
- gfpgan: 1.3.8

2023-11-09 18:27:15.475 | INFO     | lama_cleaner.parse_args:parse_args:193 - Loading installer config from D:\lama-cleaner\lama-cleaner\win_start.bat\..\installer_config.json
2023-11-09 18:27:16.617 | INFO     | lama_cleaner.parse_args:parse_args:229 - Create model cache directory: C:\Users\youri\.cache
Traceback (most recent call last):
  File "D:\lama-cleaner\lama-cleaner\installer\lib\pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\Users\\myuser\\.cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\lama-cleaner\lama-cleaner\installer\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\lama-cleaner\lama-cleaner\installer\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\lama-cleaner\lama-cleaner\installer\Scripts\lama-cleaner.exe\__main__.py", line 7, in <module>
  File "D:\lama-cleaner\lama-cleaner\installer\lib\site-packages\lama_cleaner\__init__.py", line 13, in entry_point
    args = parse_args()
  File "D:\lama-cleaner\lama-cleaner\installer\lib\site-packages\lama_cleaner\parse_args.py", line 230, in parse_args
    Path(args.model_dir).mkdir(exist_ok=True, parents=True)
  File "D:\lama-cleaner\lama-cleaner\installer\lib\pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "D:\lama-cleaner\lama-cleaner\installer\lib\pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [WinError 5] Accès refusé: 'C:\\Users\\myuser'
Appuyez sur une touche pour continuer...""

**Comment by Sanster** [comment]
Sorry for the late response, could you try changing the model download path in the configuration interface?

<img width="972" alt="image" src="https://github.com/Sanster/lama-cleaner/assets/3998421/471840d4-6d9b-453e-9354-67798ed74d0d">
