### ISSUE TITLE
[BUG]pydantic_core._pydantic_core.ValidationError: 1 validation error for Config paint_by_example_example_image   Input should be an instance of Image [type=is_instance_of, input_value=None, input_type=NoneType]

### ISSUE THREAD

**Issue by wang3680** [Sanster/IOPaint#429]
**Model**
LAMA

**Describe the bug**
[2024-01-24 09:36:41,914] ERROR in app: Exception on /inpaint [POST]
Traceback (most recent call last):
  File "E:\wss\python\pycharm-work\lama-cleaner-0.37.0\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\wss\python\pycharm-work\lama-cleaner-0.37.0\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\wss\python\pycharm-work\lama-cleaner-0.37.0\venv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "E:\wss\python\pycharm-work\lama-cleaner-0.37.0\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\wss\python\pycharm-work\lama-cleaner-0.37.0\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\wss\python\pycharm-work\lama-cleaner-0.37.0\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\wss\python\pycharm-work\lama-cleaner-0.37.0\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\wss\python\pycharm-work\lama-cleaner-0.37.0\lama_cleaner\server.py", line 259, in process
    p2p_guidance_scale=form["p2pGuidanceScale"],
  File "E:\wss\python\pycharm-work\lama-cleaner-0.37.0\venv\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
paint_by_example_example_image
  Input should be an instance of Image [type=is_instance_of, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.4/v/is_instance_of

**System Info**
(venv) E:\wss\python\pycharm-work\lama-cleaner-0.37.0>python main.py --model=lama --device=cpu --port=8085
- Platform: Windows-10-10.0.19041-SP0
- Python version: 3.7.2
- torch: 1.13.1
- Pillow: 9.5.0
- diffusers: 0.12.1
- transformers: 4.30.2
- opencv-python: 4.9.0.80
- xformers: N/A
- accelerate: 0.20.3
- lama-cleaner: N/A

2024-01-24 09:33:59.046 | INFO     | lama_cleaner.helper:load_jit_model:102 - Loading model from: C:\Users\wss\.cache\torch\hub\checkpoints\big-lama.pt
2024-01-24 09:33:59.799 | INFO     | lama_cleaner.helper:load_jit_model:102 - Loading model from: C:\Users\wss\.cache\torch\hub\checkpoints\clickseg_pplnet.
pt
 * Running on http://127.0.0.1:8085/ (Press CTRL+C to quit)
127.0.0.1 - - [24/Jan/2024 09:34:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2024 09:34:07] "GET /model HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2024 09:34:07] "GET /inputimage HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2024 09:34:07] "GET /is_desktop HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2024 09:34:07] "GET /is_disable_model_switch HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2024 09:34:07] "GET /is_enable_file_manager HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2024 09:34:07] "GET /is_enable_auto_saving HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2024 09:34:14] "GET /model HTTP/1.1" 200 -

**Comment by Sanster** [comment]
Hello, could you please try the new version? 'Lama-cleaner' has been renamed to 'iopaint'. `pip install iopaint`
