### ISSUE TITLE
How to use python to run lama cleaner to remove text with text box coordinates?

### ISSUE THREAD

**Issue by nissansz** [Sanster/IOPaint#435]
How to use python to run lama cleaner to remove text with text box coordinates?

**Comment by Sanster** [comment]
你可以使用 text box 生成黑底白字的 mask，然后使用 iopaint run 来批量处理图片

**Comment by nissansz** [comment]
Cannot run lama-cleaner-iopaint-1.0.0b2>python main.py start
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    entry_point()
  File "F:\pycharm2020.2\lama-cleaner-iopaint-1.0.0b2\iopaint\__init__.py", line 13, in entry_point
    from iopaint.cli import typer_app
  File "F:\pycharm2020.2\lama-cleaner-iopaint-1.0.0b2\iopaint\cli.py", line 5, in <module>
    from fastapi import FastAPI
  File "D:\Python3.8.8\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "D:\Python3.8.8\lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "D:\Python3.8.8\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "D:\Python3.8.8\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (D:\Python3.8.8\lib\site-packages\pydantic\fields.py)

**Comment by Sanster** [comment]
What is your pydantic version?

**Comment by nissansz** [comment]
Tried both 2.5.3, 2.5.2. Failed

**Comment by nissansz** [comment]
Any solution?

**Comment by nissansz** [comment]
Is it possible to run the lama inpaint function without fastapi, pydantic etc.?
How to do so?
