### ISSUE TITLE
[BUG] Webpage won't load

### ISSUE THREAD

**Issue by inhahe** [Sanster/IOPaint#451]
**Model**
lama

**Describe the bug**
I installed iopaint using the instructions in the readme on WSL2 (Ubuntu 22) running on Windows 11. I tried to load http://127.0.0.1:8080 in Chrome in Windows. It just loads for a long time showing nothing, then stops loading and continues to show nothing. My linux terminal shows some other stuff and then:

```
2024-02-08 16:09:29.669 | INFO     | iopaint.model_manager:init_model:39 - Loading model: lama
2024-02-08 16:09:29.670 | INFO     | iopaint.helper:load_jit_model:104 - Loading model from: /home/inhahe/.cache/torch/hub/checkpoints/big-lama.pt
INFO:     Started server process [5643]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:     127.0.0.1:56850 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:56850 - "GET /assets/index-NQyCh9rO.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56864 - "GET /assets/index-iK_rIxV0.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:53794 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:53794 - "GET /assets/index-NQyCh9rO.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:53808 - "GET /assets/index-iK_rIxV0.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:53808 - "GET /favicon.ico HTTP/1.1" 404 Not Found
```
(the two GETs are because I tried reloading the page.)

**System Info**
Software version used
1.0.4
- lama-cleaner: 
- pytorch: 2.2.0
- CUDA: n/a, it's using the CPU.

**Comment by Sanster** [comment]
It might be a bug in the front-end. Could you open Chrome's devtool and see what errors are reported in the console?

https://developer.chrome.com/docs/devtools/open?hl=zh-cn

**Comment by inhahe** [comment]
I had quit the program and WSL, so I started WSL and the program again, and this time it works. I knew I should have tried that!

However, I can't figure out how to outpaint using the web interface.

I just don't see a way to do it, so maybe the dev console logs aren't relevant, but here they are:

[127.0.0.1-1707448429378.log](https://github.com/Sanster/IOPaint/files/14216828/127.0.0.1-1707448429378.log)

**Comment by Sanster** [comment]
The side panel appears when using the Diffusion model. There are many models available in the readme, such as `runwayml/stable-diffusion-inpainting`. These models require a significant amount of computation, and running them without a GPU will be slow.

**Comment by inhahe** [comment]
Thanks. But I'm having the problem with the page not loading again.

I installed iopaint again, this time on Windows 11, Python 3.11.2. I installed it with CUDA support this time, since I do have a GPU. I ran iopaint using `iopaint start --device=cuda`. 

The same thing happens when I try to access the page in Chrome as I described earlier. 

Here's the only console errors that came up:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'getSelected')
    at jquery-1.4.min.js:188:13
content.js:7 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Array.<anonymous> (content.js:7:89199)
    at c.trigger (content.js:7:81786)
    at HTMLDocument.<anonymous> (content.js:7:81253)
```

**Comment by inhahe** [comment]
I just restarted iopaint again to try it on Firefox, and now it's working on both firefox and Chrome. So the bug seems a bit random.

**Comment by Sanster** [comment]
I don't think this should be an error of iopaint, because iopaint doesn't depend on jquery at all. Could it be the influence of other chrome plugins?

**Comment by inhahe** [comment]
Oh, hmm. I do have a few Chrome extensions running, not sure if any of them could be interfering. I guess they must be? I wouldn't know which one.

**Comment by inhahe** [comment]
I guess the problem with the page not loading and the jquery errors could be unrelated, because I don't have this problem with any other websites, and the specific error that popped up doesn't seem at glance to be one that would be likely to prevent the page from loading

**Comment by inhahe** [comment]
If the webpage ever starts failirg to load again, I'll see if there's a way I can disable all my chrome extensions and try it that way, or just try it in Firefox and get back to you.

**Comment by netoneplus** [comment]
I'm also having the same problem.
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.　（:8080/assets/index-CXO-mkQB.js:1 ）

**Comment by ziloka** [comment]
I had to download a favicon.ico file to the assets folder.

Eg since I knew iopaint was installed in this directory `C:\Users\ziloka\.pyenv\pyenv-win\versions\3.10.6\Lib\site-packages\iopaint\web_app\assets`

I downloaded a png and saved it as `favicon.ico` in that directory


After that I tried loading the page

and in the chrome dev tools i got the following error
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

I think this error is fixed if you disable cache. 

https://developer.chrome.com/docs/devtools/network/reference#disable-cache-network-conditions

**Comment by denven** [comment]
Same issue here, Python 3.12, page cannot load(blank white page) on Chrome, Edge, Firefox, and Incognito or Private mode as well. Clear or disable cache doesn't help to resolve the issue.

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

**Comment by liguob666** [comment]
同样的问题，请教如何解决呢？
index-OPzQDLhO.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
我付费购买了一个一键安装的也是一样的。git代码到本地跑起来也是一样的问题！

**Comment by robertdu86** [comment]
I had the same problem, after searching and trying thing for several hours i found here a solution that worked for me by modifying a value in regedit (https://github.com/Sanster/IOPaint/issues/460). The most ridicule thing is just after i found the solution i realised i didn't need it for what i wanted to do, batch a lot of images can be done only with a command. i post here the command for doing a lot of files with the watermark at the same position (you need a different mask for vertical photos and horizontal photos and normally if the resolution is different he does it automatically but sometimes it doesn't work because the watermark is not the rescaled so you need a different mask for that resolution creating a mask is easy you copy a foto you want to modify and open it in paint, you paint the watermark in white and the rest in black), because nothing is correctly expliqued in this site. the command is iopaint run --model=lama --device=cuda --image=C:/Watermark_a_Supprimer/image --mask=C:/Watermark_a_Supprimer/Mask/horizontal.jpg --output=C:/Watermark_a_Supprimer/output. in this case i work on the horizontal photos, so you put your photos in the folder wich the path is behind "image=" and i use the mask i called "horizontal.jpg. i must say i am very happy to have persevered trying to make this thing works because the result is fantastic.
