### ISSUE TITLE
[BUG] cudatoolkit-Downloaded bytes did not match Content-Length

### ISSUE THREAD

**Issue by Styx233** [Sanster/IOPaint#523]
**Model**
Windows 10

**Describe the bug**
当我双击win_config文件时命令行在下载cudatoolkit的时候网速很慢以至于每次都是下载失败

**Screenshots**
![QQ截图20240513221924](https://github.com/Sanster/IOPaint/assets/117528969/45179c6e-add4-41bf-bd41-cad1dc96ea0d)

**System Info**
Software version used
- lama-cleaner: 1.3.3
- pytorch:  2.1.2+cu118
- CUDA:

**Comment by Styx233** [comment]
这是第二个问题
`  Using cached rembg-2.0.56-py3-none-any.whl (32 kB)
Collecting opencv-python-headless
  Downloading opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl (38.5 MB)
     ------ --------------------------------- 6.7/38.5 MB 7.0 kB/s eta 1:16:14
ERROR: Exception:
Traceback (most recent call last):
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_vendor\urllib3\response.py", line 435, in _error_catcher
    yield
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_vendor\urllib3\response.py", line 516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\commands\install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\operations\prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\operations\prepare.py", line 483, in _prepare_linked_requirement
    local_file = unpack_url(
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\operations\prepare.py", line 165, in unpack_url
    file = get_http_url(
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\operations\prepare.py", line 106, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_vendor\urllib3\response.py", line 573, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_vendor\urllib3\response.py", line 509, in read
    with self._error_catcher():
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\pip\_vendor\urllib3\response.py", line 440, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\iopaint\cli.py:23 in           │
│ install_plugins_packages                                                                         │
│                                                                                                  │
│    20 def install_plugins_packages():                                                            │
│    21 │   from iopaint.installer import install_plugins_package                                  │
│    22 │                                                                                          │
│ >  23 │   install_plugins_package()                                                              │
│    24                                                                                            │
│    25                                                                                            │
│    26 @typer_app.command(help="Download SD/SDXL normal/inpainting model from HuggingFace")       │
│                                                                                                  │
│ D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\iopaint\installer.py:10 in     │
│ install_plugins_package                                                                          │
│                                                                                                  │
│    7                                                                                             │
│    8                                                                                             │
│    9 def install_plugins_package():                                                              │
│ > 10 │   install("rembg")                                                                        │
│   11 │   install("realesrgan")                                                                   │
│   12 │   install("gfpgan")                                                                       │
│   13                                                                                             │
│                                                                                                  │
│ D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\site-packages\iopaint\installer.py:6 in      │
│ install                                                                                          │
│                                                                                                  │
│    3                                                                                             │
│    4                                                                                             │
│    5 def install(package):                                                                       │
│ >  6 │   subprocess.check_call([sys.executable, "-m", "pip", "install", package])                │
│    7                                                                                             │
│    8                                                                                             │
│    9 def install_plugins_package():                                                              │
│                                                                                                  │
│ D:\app\IOpaint\IOpaint_Out\IOPaint-v1\installer\lib\subprocess.py:369 in check_call              │
│                                                                                                  │
│    366 │   │   cmd = kwargs.get("args")                                                          │
│    367 │   │   if cmd is None:                                                                   │
│    368 │   │   │   cmd = popenargs[0]                                                            │
│ >  369 │   │   raise CalledProcessError(retcode, cmd)                                            │
│    370 │   return 0                                                                              │
│    371                                                                                           │
│    372                                                                                           │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
CalledProcessError: Command '['D:\\app\\IOpaint\\IOpaint_Out\\IOPaint-v1\\installer\\python.exe', '-m', 'pip',
'install', 'rembg']' returned non-zero exit status 2.`

**Comment by Sanster** [comment]
感谢你支持我的开源项目，你能不能用 https://github.com/Sanster/IOPaint/blob/main/scripts/user_scripts/win_config_cn.bat 这个脚本试下，我发现其实不用装 cudatoolkit，用 `pip install torch==2.1.2 torchvision==0.16.2 --extra-index-url https://download.pytorch.org/whl/cu118` 命令装的 torch 会自带 cuda 相关库

**Comment by Styx233** [comment]
感谢您的回复，我按照您给出的bat脚本执行了，执行结束可以成功打开配置页面，但是我看到命令行中提示错误信息
![Uploading 批注 2024-05-16 042057.png…]()

**Comment by Sanster** [comment]
你的截图没有上传成功。。。如果可以打开配置页面，也能够成功保存配置，那命令行中的提示应该是可以忽略的

**Comment by Styx233** [comment]
谢谢解答，已经成功执行了，错误警告消失了！不过我还有一个问题：假设100张图片的水印都在同一个位置，我应该如何批量移除这些水印呢？我看操作说明里面写的是执行命令，在Windows上如何操作呢？
