### ISSUE TITLE
Getting Error While Starting PowerPaint V2

### ISSUE THREAD

**Issue by RFedz007989** [Sanster/IOPaint#527]
Hi,

I am getting this while starting PowerPaint V2. Kindly check the below error.

(Traceback (most recent call last):
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\anyio\streams\memory.py", line 97, in receive
    return self.receive_nowait()
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\anyio\streams\memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\anyio\streams\memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\iopaint\api.py", line 113, in exception_handling
    return await call_next(request)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\starlette\_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\starlette\_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\starlette\routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\starlette\routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\starlette\_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\starlette\_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\starlette\routing.py", line 70, in app
    response = await func(request)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\fastapi\routing.py", line 299, in app
    raise e
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\fastapi\routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\starlette\concurrency.py", line 35, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\iopaint\api.py", line 271, in api_inpaint
    rgb_np_img = self.model_manager(image, mask, req)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\iopaint\model_manager.py", line 107, in __call__
    return self.model(image, mask, config).astype(np.uint8)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\iopaint\model\base.py", line 295, in __call__
    inpaint_result = self._scaled_pad_forward(image, mask, config)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\iopaint\model\base.py", line 372, in _scaled_pad_forward
    inpaint_result = self._pad_forward(downsize_image, downsize_mask, config)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\iopaint\model\base.py", line 70, in _pad_forward
    result = self.forward(pad_image, pad_mask, config)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\iopaint\model\power_paint\power_paint_v2.py", line 162, in forward
    output = self.model(
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\iopaint\model\power_paint\v2\pipeline_PowerPaint_Brushnet_CA.py", line 1579, in __call__
    self.brushnet(
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\iopaint\model\power_paint\v2\BrushNet_CA.py", line 922, in forward
    sample = self.conv_in_condition(brushnet_cond)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\IOpaint\IOPaint-v1\installer\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 9, 3, 3], expected input[2, 14, 89, 64] to have 9 channels, but got 14 channels instead
INFO:     127.0.0.1:1935 - "POST /api/v1/inpaint HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:1935 - "GET /api/v1/server-config HTTP/1.1" 200 OK)

Thank You

**Comment by CyrusVorwald** [comment]
I get the same error

**Comment by RFedz007989** [comment]
> I was getting the same error and changed the sampler to fix it. My guess is that the sampler you are trying to use does not work with the model.
> 
> Nevermind, it is occurring again after I restarted and I don't know why.

I am using sampler Euler A. What sampler you used to fix this issue & which model you used.

Thank You

**Comment by CyrusVorwald** [comment]
I think it works if you don't use an inpainting model. I am not sure how to get it to work with an inpainting model.

**Comment by RFedz007989** [comment]
> I think it works if you don't use an inpainting model. I am not sure how to get it to work with an inpainting model.

Thanks. Can you tell me which non inpainting model should I use.

**Comment by jryebread** [comment]
what command are you using to run powerpaintv2?
